### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wolneykien** [sv99/rastertokpsl-re#2]
Hi! What is the license policy for the project? Is it free and open source software?

**Comment by sv99** [comment]
Its free. Have problem with my printer and made it for myself.

**Comment by wolneykien** [comment]
Excuse me, but in order to **redistribute** your work and/or to continue the development you've started, it would be nice to know what is the licensing policy in particular. Is it WTFPL (https://en.wikipedia.org/wiki/WTFPL), or BSD-like or GNU GPL v2, v3?

**Comment by wolneykien** [comment]
P.S. You also have an issue with the modified version of the PPD. The head of the `Kyocera_FS-1020MFPGDI_RE.ppd` — the _modified_ version of `Kyocera_FS-1020MFPGDI.ppd` states that the file can't be modified in any way. I suggest you to use a symlink:

    $ ls -l /usr/lib/cups/filter/rastertokpsl
    lrwxrwxrwx 1 root root 15 ноя  6 19:19 /usr/lib/cups/filter/rastertokpsl -> rastertokpsl-re

And not to modify the PPD at all. Then, in order to switch to the original proprietary filter, you can just switch the symlink:

    $ ls -l /usr/lib/cups/filter/rastertokpsl
    lrwxrwxrwx 1 root root 15 ноя  6 19:19 /usr/lib/cups/filter/rastertokpsl -> rastertokpsl.orig

where `rastertokpsl.orig` is the renamed copy of the original Kyocera filter.
